   
name: Build base image and push to DockerHub.

on:
  workflow_dispatch:
  
env:
  DOCKER_REPOSITORY: aws-brand-sentiment-base-image
  IMAGE_TAG: latest

jobs:
      
  build-and-push:
    name: Build and Push to DockerHub Registry
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Docker Login
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and Push Base Image
        uses: docker/build-push-action@v2
        with:
          file: app/backend/Dockerfile
          context: app/
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/python-grading-script-base:2.0
