   
name: Build base image and push to DockerHub

on:
  workflow_dispatch:

env:
  REPOSITORY: aws-brand-sentiment-base-image
  IMAGE_TAG: latest

jobs:
      
  build-and-push:
    name: Build and push to DockerHub
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Docker login
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build AMD image and push
        uses: docker/build-push-action@v2.10.0
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
             ${{ secrets.DOCKER_USERNAME }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
