   
name: Build base image and push to DockerHub.

on:
  workflow_dispatch:
  
jobs:
      
  build-and-push:
    name: Build and Push to DockerHub Registry
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Docker Login
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and Push Base Image
        env:
          REGISTRY: ${{ secrets.DOCKER_USERNAME }}
          REPOSITORY: aws-brand-sentiment-base-image
          IMAGE_TAG: latest
        uses: docker/build-push-action@v2.10.0
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            $REGISTRY/$REPOSITORY:$IMAGE_TAG
